"""Add scraper_config to stations

Revision ID: 126d8780a238
Revises: 348b94b43609
Create Date: 2025-12-13 13:15:25.105824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126d8780a238'
down_revision = '348b94b43609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('scraper_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'scraper_config')
    # ### end Alembic commands ###
