"""initial_sqlite

Revision ID: 14e8a27880aa
Revises: 
Create Date: 2026-06-29 10:16:46.225743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e8a27880aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('scraper_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_id'), ['id'], unique=False)

    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_prices_id'), ['id'], unique=False)

    op.create_table('fuel_prices_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_prices_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_prices_archive_fuel_type'), ['fuel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_prices_archive_id'), ['id'], unique=False)
        batch_op.create_index('ix_fuel_prices_archive_station_fuel_created', ['station_id', 'fuel_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_prices_archive_station_id'), ['station_id'], unique=False)

    op.create_table('station_opening_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('station_opening_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_opening_hours_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_opening_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_opening_hours_id'))

    op.drop_table('station_opening_hours')
    with op.batch_alter_table('fuel_prices_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_prices_archive_station_id'))
        batch_op.drop_index('ix_fuel_prices_archive_station_fuel_created')
        batch_op.drop_index(batch_op.f('ix_fuel_prices_archive_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_prices_archive_fuel_type'))

    op.drop_table('fuel_prices_archive')
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_prices_id'))

    op.drop_table('fuel_prices')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_id'))

    op.drop_table('stations')
    # ### end Alembic commands ###
