"""add station_opening_hours

Revision ID: 348b94b43609
Revises: a79b33009629
Create Date: 2025-12-06 11:46:55.061973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348b94b43609'
down_revision = 'a79b33009629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_opening_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_opening_hours_id'), 'station_opening_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_opening_hours_id'), table_name='station_opening_hours')
    op.drop_table('station_opening_hours')
    # ### end Alembic commands ###
