"""initial

Revision ID: 74c061fd8084
Revises: 2f119c5e72e2
Create Date: 2025-11-29 14:05:57.588827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c061fd8084'
down_revision = '2f119c5e72e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('website_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'website_url')
    # ### end Alembic commands ###
