"""Fix archive index – remove from main table, add to archive

Revision ID: 7adae87b4eb2
Revises: 85b1ed9b790f
Create Date: 2026-01-03 12:55:25.182274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adae87b4eb2'
down_revision = '85b1ed9b790f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archive_station_fuel_created'), table_name='fuel_prices')
    op.alter_column('fuel_prices_archive', 'price',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.create_index('ix_fuel_prices_archive_station_fuel_created', 'fuel_prices_archive', ['station_id', 'fuel_type', 'created_at'], unique=False)
    op.drop_constraint(op.f('fuel_prices_archive_station_id_fkey'), 'fuel_prices_archive', type_='foreignkey')
    op.create_foreign_key(None, 'fuel_prices_archive', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_prices_archive', type_='foreignkey')
    op.create_foreign_key(op.f('fuel_prices_archive_station_id_fkey'), 'fuel_prices_archive', 'stations', ['station_id'], ['id'])
    op.drop_index('ix_fuel_prices_archive_station_fuel_created', table_name='fuel_prices_archive')
    op.alter_column('fuel_prices_archive', 'price',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=False)
    op.create_index(op.f('ix_archive_station_fuel_created'), 'fuel_prices', ['station_id', 'fuel_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
