"""Add fuel_prices_archive table

Revision ID: 85b1ed9b790f
Revises: d5bbad408c00
Create Date: 2026-01-03 12:51:01.155988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b1ed9b790f'
down_revision = 'd5bbad408c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_archive_station_fuel_created', 'fuel_prices', ['station_id', 'fuel_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_archive_station_fuel_created', table_name='fuel_prices')
    # ### end Alembic commands ###
