"""add last_updated to stations

Revision ID: a79b33009629
Revises: 74c061fd8084
Create Date: 2025-12-06 11:23:54.242717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a79b33009629'
down_revision = '74c061fd8084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_prices', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('fuel_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('stations', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('stations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('stations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'updated_at')
    op.drop_column('stations', 'created_at')
    op.drop_column('stations', 'last_updated')
    op.alter_column('fuel_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('fuel_prices', 'created_at')
    # ### end Alembic commands ###
