"""Add fuel_prices_archive table

Revision ID: b141b9ae39b1
Revises: 7adae87b4eb2
Create Date: 2026-01-03 12:58:08.878917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b141b9ae39b1'
down_revision = '7adae87b4eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
