"""Add fuel_prices_archive table

Revision ID: d5bbad408c00
Revises: 126d8780a238
Create Date: 2026-01-03 12:37:01.425977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bbad408c00'
down_revision = '126d8780a238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_prices_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_prices_archive_fuel_type'), 'fuel_prices_archive', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_fuel_prices_archive_id'), 'fuel_prices_archive', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_archive_station_id'), 'fuel_prices_archive', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_prices_archive_station_id'), table_name='fuel_prices_archive')
    op.drop_index(op.f('ix_fuel_prices_archive_id'), table_name='fuel_prices_archive')
    op.drop_index(op.f('ix_fuel_prices_archive_fuel_type'), table_name='fuel_prices_archive')
    op.drop_table('fuel_prices_archive')
    # ### end Alembic commands ###
